### ISSUE TITLE
Exporting sub-collections are not nested

### ISSUE THREAD

**Issue by tmk1991** [codediodeio/firestore-migrator#10]
When exporting a sub-collection they end up at the root level of the export, not inside of the parent document.

**Before**:
`
const subCollections = await getCollections(subCollPaths);
_.assign(doc, subCollections);
`

**Suggestion**:

`const subCollections = await getCollections(subCollPaths);
for(let col in subCollections) {
    doc[snap.id][col] = subCollections[col];
}
`

**Comment by samiq** [comment]
this is already fixed, can someone close this bug?

**Comment by tmk1991** [comment]
@samiq  it's fixed in the PR
