### ISSUE TITLE
Feature: Export as CSV or Excel

### ISSUE THREAD

**Issue by codediodeio** [codediodeio/firestore-migrator#11]
We should also include the ability to export as CSV or xlsx.

**Comment by stildalf** [comment]
The PR added support for exporting a single collection to CSV file or single sheet XLSX doc as well as selected/all collections to indexed CSV/XLSX files.

Exporting multiple or all collections to:
- CSV separates all collections and includes an ~.INDEX.csv file
- XLSX, single document, sheet per collections and includes an INDEX sheet

You can then import either the whole indexed export or selected collections (even nested). 

Single/Selected/All collections can also be exported/imported to/from a JSON file.

**Comment by samiq** [comment]
can someone close this ticket as it's already been merged into the code?
