### ISSUE TITLE
import a collection that has sub-collections

### ISSUE THREAD

**Issue by SogoGolf** [codediodeio/firestore-migrator#22]
hi, is it possible to import a collection (eg in json data format) and have the import "recognise" that the collection also has sub-collections (and so those sub collections get created for you too) ?

**Comment by stildalf** [comment]
Hi, it certainly does import collections and sub-collections. Perhaps the easiest is to export a sample containing the structure you need and then investigate the resulting export. You can export/import from JSON with a (sub)collection tree or CSV & Excel with (sub)collections per flat file or sheet.

**Comment by SogoGolf** [comment]
Awesome stuff thanks I'll give a try

**Comment by karanjasani8899** [comment]
> Hi, it certainly does import collections and sub-collections. Perhaps the easiest is to export a sample containing the structure you need and then investigate the resulting export. You can export/import from JSON with a (sub)collection tree or CSV & Excel with (sub)collections per flat file or sheet.

Can you explain to me in Detail?
Thanks.
