### ISSUE TITLE
fire-migrate : The term 'fire-migrate' is not recognized

### ISSUE THREAD

**Issue by super9xman** [codediodeio/firestore-migrator#25]
I am getting the following error when I try to run any fire-migrate cmd in the cli....

error:
fire-migrate : The term 'fire-migrate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ fire-migrate import --dry-run test.json myCollection
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (fire-migrate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by super9xman** [comment]
fixed

**Comment by murali-vutti** [comment]
How did you solved the issue

**Comment by stildalf** [comment]
Be sure to run:
`npm run build-link`
which'll map `fire-migrate` as per the `bin` entry in package.json.
