### ISSUE TITLE
Unhandled promise rejection (rejection id: 1): TypeError: Object.entries is not a function

### ISSUE THREAD

**Issue by FredvanRijswijk** [codediodeio/firestore-migrator#9]
when exporting ```fire-migrate export users-posts.json users``` I get a file, when I want to import ``` fire-migrate i users-posts.json users.```  the same file I get ```Unhandled promise rejection (rejection id: 1): TypeError: Object.entries is not a function```

**Comment by FredvanRijswijk** [comment]
@stildalf Yes is the same:

```
{
    "compilerOptions": {
        "outDir": "./dist/",
        "noImplicitAny": false,
        "module": "commonjs",
        "target": "es5",
        "allowJs": true,
        "sourceMap": true,
        "moduleResolution": "node",
        "lib": [
            "es2017"
        ],
        "types": [
            "node"
        ]
    },
    "include": [
        "src/**/*"
    ]
}

```

**Comment by stildalf** [comment]
Don't think I can assist much more @FredvanRijswijk.  I would think it's something in your environment.  Object.entries() is fairly new, hence the es2017 spec. But you seem to have that down. 

Maybe a global tsconfig is affecting you, try: `tsc -p ./tsconfig.json` from within the ./firestore-migrator folder.

What OS, node and ts versions are you on?

**Comment by FredvanRijswijk** [comment]
OS: 10.13.4 (17E199)
Node: v6.11.5
TSC: Version 2.2.1

**Comment by FredvanRijswijk** [comment]
It was my node version, updated to node version 8.11.1 and now it works
